// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpLqaEDEnlpIubUfDAhoK4oQXlA5wbwM',
    appId: '1:21828788357:web:bd880806a1b06e3085c9ec',
    messagingSenderId: '21828788357',
    projectId: 'deliveryapp-8a7e4',
    authDomain: 'deliveryapp-8a7e4.firebaseapp.com',
    storageBucket: 'deliveryapp-8a7e4.firebasestorage.app',
    measurementId: 'G-M44D30GHPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcZzk0D4IcHFzTGACMgqVCerIs0p1HuY',
    appId: '1:21828788357:android:47832e5c97cacad185c9ec',
    messagingSenderId: '21828788357',
    projectId: 'deliveryapp-8a7e4',
    storageBucket: 'deliveryapp-8a7e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQO605ssB_arey35qy0LNcLHbExTHDZ8Q',
    appId: '1:21828788357:ios:603abffec9c142b085c9ec',
    messagingSenderId: '21828788357',
    projectId: 'deliveryapp-8a7e4',
    storageBucket: 'deliveryapp-8a7e4.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQO605ssB_arey35qy0LNcLHbExTHDZ8Q',
    appId: '1:21828788357:ios:603abffec9c142b085c9ec',
    messagingSenderId: '21828788357',
    projectId: 'deliveryapp-8a7e4',
    storageBucket: 'deliveryapp-8a7e4.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARpLqaEDEnlpIubUfDAhoK4oQXlA5wbwM',
    appId: '1:21828788357:web:e735d5b58fde1e8b85c9ec',
    messagingSenderId: '21828788357',
    projectId: 'deliveryapp-8a7e4',
    authDomain: 'deliveryapp-8a7e4.firebaseapp.com',
    storageBucket: 'deliveryapp-8a7e4.firebasestorage.app',
    measurementId: 'G-ZX0J24JMW9',
  );
}
